<a href="https://colab.research.google.com/github/dreamer561/Python/blob/main/Numpy_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=[2,2,2,2]
b=[3,3,3,3]
c=[]
for i in range (len(a)):
    c.append(a[i]*b[i])
print(c)

[6, 6, 6, 6]


In [ ]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(type(a))
b=np.array([6,7,8])
print(b)
print(type(b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>


In [113]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
a=np.array([2,3,4])
print(a.dtype.name)
b=np.array([2.3,2.4,3.5])
print(b)
print(b.dtype.name)

int64
[2.3 2.4 3.5]
float64


In [ ]:
#printing 2d array
import numpy as num
a=num.array([(1.2,2.2,3.2),(2,3,4)])
print(a)

[[1.2 2.2 3.2]
 [2.  3.  4. ]]


In [ ]:
#printing 2d array
import numpy as num
# a=num.array([(1.2,2.2,3.2),(2,3,4)],dtype=complex)
# print(a)
# a=num.ones((5,4))
# print(a.size)
a=num.ones((2,5,4),dtype=num.int16)
print(a)
# b=num.empty((4,4))
# print(b)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
num.empty((2,3))

array([[1.2, 2.2, 3.2],
       [2. , 3. , 4. ]])

In [ ]:
num.arange(5,500,10)

array([  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105, 115, 125,
       135, 145, 155, 165, 175, 185, 195, 205, 215, 225, 235, 245, 255,
       265, 275, 285, 295, 305, 315, 325, 335, 345, 355, 365, 375, 385,
       395, 405, 415, 425, 435, 445, 455, 465, 475, 485, 495])

In [ ]:
# num.arange(5,500,1.8)

In [ ]:
from numpy import pi
np.linspace(2,6,18)
x=np.linspace(0,2*pi,100)
# print(x)
f=np.sin(x)
# print(x)

In [ ]:
a=num.zeros_like((3,3,9))
print(a)
num.empty((4,5))

[0 0 0]


array([[2.23126528e-316, 5.18768928e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.16095484e-028, 4.91461113e+252, 1.64346732e+161,
        7.20358919e+159, 9.29846533e+242],
       [2.58400946e+161, 2.53277491e-086, 4.35287203e-114,
        1.75300433e+243, 4.90910702e-109],
       [6.48224637e+170, 3.67145870e+228, 3.29832587e-033,
        6.17582057e-322, 0.00000000e+000]])

printing arrays


In [ ]:
a=np.arange(6)
print(a)
b=np.arange(12).reshape(4,3)
print(b)
c=np.arange(24).reshape(2,3,4)
print(c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)
np.arange(10000)
a=np.arange(10000).reshape(100,100)
# print(a)

Basic operatios

In [ ]:
#arthematic
a=np.array([20,30,40,50])
b=np.arange(4)
c=a+b
print(c)
b**2
10*np.sin(a)
a<45


[20 31 42 53]


array([ True,  True,  True, False])

In [ ]:
a=np.array([[1,1],
        [0,1]])
b=np.array([[2,0],
        [3,4]])
a*b

array([[2, 0],
       [0, 4]])

Indexing and selection


In [ ]:
import numpy as np
arrays=np.arange(15)
print(arrays)
arrays[4]
#broadcasting
arrays[0:5]=100
print(arrays)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[100 100 100 100 100   5   6   7   8   9  10  11  12  13  14]


In [ ]:
#Resetting again the array
arr=np.arange(12)#.reshape(4,3)
print(arr)
#slice of array
slice_af_arr=arr[0:6]
print(slice_af_arr)
slice_af_arr[1:5]=99
print(slice_af_arr)

#access all elements
# arr[:]=1
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5]
[ 0 99 99 99 99  5]
[ 0 99 99 99 99  5  6  7  8  9 10 11]


#2Slicing solution

In [ ]:
#copy existing array with help of .copy()
arr=np.arange(12)
arr_copy=arr.copy()
arr_copy[0:6]=99
print(arr_copy)
print(arr)

[99 99 99 99 99 99  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


INDEXING 2D ARRAY

In [ ]:
arr2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#accessing 1st row
print(arr2d[0])
#accessing single element
print(arr2d[1][1])

#or
print(arr2d[1,1])

[ 5 10 15]
25
25


#Slicing 2d ARRAY

In [61]:
#to extract 2d array from giving array
print(arr2d)
print(arr2d[:2,1:])

#x:-[include x and after x]
#:x[exclude x and before x]
print(arr2d[2:,:2])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[10 15]
 [25 30]]
[[35 40]]


In [81]:
#[5,10]
#[20,25]
print(arr2d[:2,:2])
length=arr2d.shape[1]

[[0. 0.]
 [0. 0.]]


In [90]:
#4Fancy Indexing
import numpy as np
# Fancy_array=np.arange(15).reshape(3,5)
# Fancy_array
arr2d=np.zeros((10,10))
length=arr2d.shape[1]
for i in range(length):
  arr2d[i]=i
print(arr2d)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]


In [91]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [92]:
arr2d[[7]]

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

#Selection

In [94]:
arr=np.arange(1,17)
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [97]:
arr[arr > 3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [106]:
#6--Numpy_Operations
arr=np.arange(0,10)
arr
#addition
arr+arr
#sub
arr-arr
#mul
arr*arr
#div
arr/arr
#exponent
arr**3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [111]:
#Universal functions
#root
np.sqrt(arr)
#exponential
np.exp(arr)
np.exp2(arr)
#finding max af array
np.max(arr)
#finding min
np.min(arr)

0

In [112]:
#trigonamatry function
np.sin(arr)
#log
np.log(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])